---
- hosts: "bckp"
  become: true
  gather_facts: yes
  
  tasks: 
# prepeare system  
  - name: INSTALL mc
    yum: name=mc state=present

# install borgbackup
  - name: INSTALL EPEL-RELEASE REPO
    yum: name=epel-release state=present

  - name: INSTALL BORGBACKUP
    yum: name=borgbackup state=present
    
  - name: Add user borg
    user: 
      name: borg
      generate_ssh_key: true

  - name: create partition
    parted:
      device: /dev/sdb
      number: 1
      state: present

  - filesystem:
      fstype: ext4
      dev: /dev/sdb1

  - name: moint disk
    mount:
      path: /var/backup/
      src: /dev/sdb1
      state: mounted
      fstype: ext4

  - name: create backup dir
    file:
      path: /var/backup/
      state: directory
      owner: borg
      group: borg
      mode: '0755'

  - name: Recursively remove directory
    file:
      path: /var/backup/lost+found
      state: absent

  - name: create ssh dir
    file:
      path: /home/borg/.ssh/
      state: directory
      owner: borg
      group: borg
      mode: '0700'

  - name: COPY authorized_keys 
    copy:
      src: cnfgs/authorized_keys
      dest: /home/borg/.ssh/authorized_keys

  - name: COPY rights authorized_keys file
    file:
      path: /home/borg/.ssh/authorized_keys
      state: touch
      owner: borg
      group: borg
      mode: '0600'
       